spring:
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              create-target: local/db/01-create-tables.sql
              action: create
            create-source: metadata