spring:
  application:
    name: example
  datasource:
    url: jdbc:postgresql://localhost:9432/example
    username: root
    password: root
  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: none

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    ttl-in-millis: 3600000

server:
  port: 9090
  servlet:
    context-path: /example/api

springdoc:
  swagger-ui:
    defaultModelsExpandDepth: -1
    doc-expansion: none